export type GalleryCategory =
  | "All"
  | "Minimal"
  | "French"
  | "Nail Art"
  | "Chrome"
  | "Gel & Care"
  | "Editorial";

export interface GalleryItem {
  id: string;
  title: string;
  category:
    "Minimal" | "French" | "Nail Art" | "Chrome" | "Gel & Care" | "Editorial";
  src: string;
  alt: string;
  aspect: "portrait" | "landscape" | "square";
  width: number;
  height: number;
  technique: string;
  finish: string;
  nailShape: string;
  featured: boolean;
  layer: number;
}

export const GALLERY_ITEMS: GalleryItem[] = [
  {
    id: "work-001",
    title: "Liquid Champagne Chrome French",
    category: "French",
    src: "/gallery/work-001.svg",
    alt: "Almond shaped nails featuring sheer warm nude base with liquid champagne chrome micro French tips",
    aspect: "portrait",
    width: 800,
    height: 1000,
    technique: "Micro French · Glazed Chrome · Hard Gel",
    finish: "High-Gloss Mirror",
    nailShape: "Almond",
    featured: true,
    layer: 1,
  },
  {
    id: "work-002",
    title: "Oat Milk & Micro Gold Foil",
    category: "Minimal",
    src: "/gallery/work-002.svg",
    alt: "Clean oval nails in milky oat-nude gel accented with delicate flecks of 24k gold leaf",
    aspect: "square",
    width: 800,
    height: 800,
    technique: "Structured BIAB · 24K Leaf · E-File Manicure",
    finish: "Satin Sheen",
    nailShape: "Oval",
    featured: true,
    layer: 2,
  },
  {
    id: "work-003",
    title: "Tortoiseshell & Amber Glass",
    category: "Nail Art",
    src: "/gallery/work-003.svg",
    alt: "Rich tortoiseshell art on square-oval nails with translucent amber jelly and deep espresso layers",
    aspect: "portrait",
    width: 800,
    height: 1000,
    technique: "Layered Jelly Gel · Hand-Painted Inks",
    finish: "High-Gloss Glass",
    nailShape: "Squoval",
    featured: true,
    layer: 3,
  },
  {
    id: "work-004",
    title: "Glazed Donut Pearl Shimmer",
    category: "Chrome",
    src: "/gallery/work-004.svg",
    alt: "Almond nails with an ethereal white pearl chrome glaze over sheer blush nude",
    aspect: "landscape",
    width: 1000,
    height: 750,
    technique: "Pearl Chrome Powder · Sheer Nude Base",
    finish: "Iridescent Glaze",
    nailShape: "Almond",
    featured: true,
    layer: 1,
  },
  {
    id: "work-005",
    title: "Japanese Structured BIAB Neutral",
    category: "Gel & Care",
    src: "/gallery/work-005.svg",
    alt: "Impeccably clean Russian e-file manicure with natural nude Japanese structured gel apex",
    aspect: "square",
    width: 800,
    height: 800,
    technique: "Apex Alignment · Cuticle E-File · Japanese Gel",
    finish: "Natural Gloss",
    nailShape: "Round",
    featured: true,
    layer: 2,
  },
  {
    id: "work-006",
    title: "Obsidian Velvet Cat-Eye",
    category: "Editorial",
    src: "/gallery/work-006.svg",
    alt: "Sculpted coffin nails with multidimensional velvet magnetic cat-eye shimmer over obsidian black",
    aspect: "portrait",
    width: 800,
    height: 1000,
    technique: "Magnetic Cat-Eye · Deep Jet Pigment",
    finish: "Dimensional Velvet",
    nailShape: "Coffin",
    featured: true,
    layer: 4,
  },
  {
    id: "work-007",
    title: "Negative Space Architectural Line",
    category: "Minimal",
    src: "/gallery/work-007.svg",
    alt: "Sheer beige almond nails featuring ultra-crisp black and rose-gold negative space geometric lines",
    aspect: "portrait",
    width: 800,
    height: 1000,
    technique: "Precision Linework · Clean Cuticle Border",
    finish: "Matte & Gloss Contrast",
    nailShape: "Almond",
    featured: true,
    layer: 1,
  },
  {
    id: "work-008",
    title: "Bordeaux Wine Deep Gloss",
    category: "Gel & Care",
    src: "/gallery/work-008.svg",
    alt: "Square manicured nails in rich deep bordeaux wine lacquer with mirror glass topcoat",
    aspect: "square",
    width: 800,
    height: 800,
    technique: "Double-Coat Pigment · Russian Manicure",
    finish: "Ultra-Lacquer Wet Look",
    nailShape: "Square",
    featured: true,
    layer: 2,
  },
  {
    id: "work-009",
    title: "Silver Molten Liquid Metal",
    category: "Chrome",
    src: "/gallery/work-009.svg",
    alt: "High-editorial stiletto nails with sculpted 3D molten silver liquid chrome running down nude base",
    aspect: "portrait",
    width: 800,
    height: 1000,
    technique: "3D Chrome Gel · Sculpted Freehand Drips",
    finish: "Liquid Chrome 3D",
    nailShape: "Stiletto",
    featured: true,
    layer: 3,
  },
  {
    id: "work-010",
    title: "Italian Carrara White Marble",
    category: "Nail Art",
    src: "/gallery/work-010.svg",
    alt: "Soft Carrara white marble nail art with delicate grey smoke veining and gold metallic flecks",
    aspect: "landscape",
    width: 1000,
    height: 750,
    technique: "Blooming Gel · Quartz Inks · Gold Leaf Accent",
    finish: "Porcelain Gloss",
    nailShape: "Almond",
    featured: true,
    layer: 1,
  },
  {
    id: "work-011",
    title: "Rose Quartz Healing Crystal",
    category: "Nail Art",
    src: "/gallery/work-011.svg",
    alt: "Ethereal translucent rose quartz nail design with crystalline fractures and subtle iridescent glow",
    aspect: "portrait",
    width: 800,
    height: 1000,
    technique: "Layered Jelly Rose · White Crystal Veins",
    finish: "Translucent Gemstone",
    nailShape: "Almond",
    featured: true,
    layer: 2,
  },
  {
    id: "work-012",
    title: "Micro-Dot Minimalist Accent",
    category: "Minimal",
    src: "/gallery/work-012.svg",
    alt: "Barely-there blush pink gel base punctuated with single obsidian micro dots at the cuticle moon",
    aspect: "square",
    width: 800,
    height: 800,
    technique: "Dotting Tool Precision · Sheer Pink BIAB",
    finish: "High-Gloss Glass",
    nailShape: "Round",
    featured: true,
    layer: 3,
  },
  {
    id: "work-013",
    title: "Double Skinny French Vanilla",
    category: "French",
    src: "/gallery/work-013.svg",
    alt: "Contemporary double French manicure with twin ultra-fine vanilla and ivory smile lines",
    aspect: "portrait",
    width: 800,
    height: 1000,
    technique: "Dual Micro Line · Soft French Pink Base",
    finish: "Porcelain Shine",
    nailShape: "Almond",
    featured: false,
    layer: 1,
  },
  {
    id: "work-014",
    title: "Espresso Mocha Glaze",
    category: "Gel & Care",
    src: "/gallery/work-014.svg",
    alt: "Glossy dark espresso mocha gel nails on clean square shape with flawless cuticle contouring",
    aspect: "square",
    width: 800,
    height: 800,
    technique: "Deep Mocha Gel · Top Tier Cuticle Cleanse",
    finish: "Caramel Mirror",
    nailShape: "Square",
    featured: false,
    layer: 2,
  },
  {
    id: "work-015",
    title: "Aura Sunset Holographic Fade",
    category: "Editorial",
    src: "/gallery/work-015.svg",
    alt: "Airbrushed aura nail art radiating soft terracotta, peony pink and lavender beneath crystal topcoat",
    aspect: "portrait",
    width: 800,
    height: 1000,
    technique: "Airbrush Gradient · Holo Chrome Dust",
    finish: "Soft-Focus Aura",
    nailShape: "Almond",
    featured: false,
    layer: 3,
  },
  {
    id: "work-016",
    title: "Frosted Matte Cashmere",
    category: "Minimal",
    src: "/gallery/work-016.svg",
    alt: "Soft cashmere taupe squoval nails sealed with a luxurious velvety touch matte topcoat",
    aspect: "landscape",
    width: 1000,
    height: 750,
    technique: "Cashmere Pigment · Velvet Matte Finish",
    finish: "Velvety Matte",
    nailShape: "Squoval",
    featured: false,
    layer: 1,
  },
  {
    id: "work-017",
    title: "Golden Hour Celestial Starlight",
    category: "Nail Art",
    src: "/gallery/work-017.svg",
    alt: "Delicate four-point gold starlight motifs and miniature pearls hand-painted across nude canvas",
    aspect: "portrait",
    width: 800,
    height: 1000,
    technique: "Hand-Painted Starbursts · Micro Pearls",
    finish: "Glistening Dew",
    nailShape: "Almond",
    featured: false,
    layer: 2,
  },
  {
    id: "work-018",
    title: "Rose Gold Chrome Mirror",
    category: "Chrome",
    src: "/gallery/work-018.svg",
    alt: "Full-coverage rose gold mirror chrome nails reflecting studio lighting with seamless clarity",
    aspect: "square",
    width: 800,
    height: 800,
    technique: "High-Adhesion Base · Rose Gold Pigment",
    finish: "Pure Metallic Reflection",
    nailShape: "Almond",
    featured: false,
    layer: 3,
  },
  {
    id: "work-019",
    title: "Forest Olive Modern French",
    category: "French",
    src: "/gallery/work-019.svg",
    alt: "Sophisticated deep forest olive French tips delicately curved on elegant oval natural nails",
    aspect: "portrait",
    width: 800,
    height: 1000,
    technique: "Deep Olive Pigment · Cream Base",
    finish: "Satin Cream",
    nailShape: "Oval",
    featured: false,
    layer: 1,
  },
  {
    id: "work-020",
    title: "3D Clear Dew Drops",
    category: "Editorial",
    src: "/gallery/work-020.svg",
    alt: "Sculpted transparent 3D water droplets suspended atop iridescent sea-glass sheer blue nails",
    aspect: "portrait",
    width: 800,
    height: 1000,
    technique: "Hard Sculpture Gel · Raindrop Embossing",
    finish: "Wet Glass Drops",
    nailShape: "Almond",
    featured: false,
    layer: 4,
  },
  {
    id: "work-021",
    title: "Milky Cloud Ombré Fade",
    category: "Gel & Care",
    src: "/gallery/work-021.svg",
    alt: "Flawless baby boomer gradient fading seamlessly from sheer warm beige to milky white tip",
    aspect: "square",
    width: 800,
    height: 800,
    technique: "Baby Boomer Sponge Blend · Builder Gel",
    finish: "Seamless Milky Gradient",
    nailShape: "Almond",
    featured: false,
    layer: 2,
  },
  {
    id: "work-022",
    title: "Botanical Sage Fine Vine",
    category: "Nail Art",
    src: "/gallery/work-022.svg",
    alt: "Hand-painted organic sage botanical vine winding along natural sheer nude almond manicure",
    aspect: "portrait",
    width: 800,
    height: 1000,
    technique: "000 Fine Liner Brush · Organic Olive Ink",
    finish: "Porcelain Gloss",
    nailShape: "Almond",
    featured: false,
    layer: 1,
  },
  {
    id: "work-023",
    title: "Smoky Quartz Translucent Glass",
    category: "Minimal",
    src: "/gallery/work-023.svg",
    alt: "Translucent smoky quartz jelly gel on squoval nails showing healthy natural nail line underneath",
    aspect: "landscape",
    width: 1000,
    height: 750,
    technique: "Translucent Brown Syrup Gel · E-File Cuticle",
    finish: "Smoky Gloss",
    nailShape: "Squoval",
    featured: false,
    layer: 2,
  },
  {
    id: "work-024",
    title: "Molten Gold Cuticle Outline",
    category: "French",
    src: "/gallery/work-024.svg",
    alt: "Reverse French cuff featuring embossed molten gold metallic lining hugging the cuticle curve",
    aspect: "portrait",
    width: 800,
    height: 1000,
    technique: "Reverse French Line · Raised Metallic Paste",
    finish: "Embossed 24K Gold",
    nailShape: "Oval",
    featured: false,
    layer: 3,
  },
  {
    id: "work-025",
    title: "Pure Alabaster Structured Overlay",
    category: "Gel & Care",
    src: "/gallery/work-025.svg",
    alt: "Crisp architectural square nails in clean alabaster white with flawless reflection lines",
    aspect: "square",
    width: 800,
    height: 800,
    technique: "Russian E-File · Pure Alabaster Pigment",
    finish: "Clean High Gloss",
    nailShape: "Square",
    featured: false,
    layer: 1,
  },
  {
    id: "work-026",
    title: "Blue Hour Iridescent Aura",
    category: "Editorial",
    src: "/gallery/work-026.svg",
    alt: "Deep twilight blue aura center softly diffusing outwards into cool sheer mist on long coffin nails",
    aspect: "portrait",
    width: 800,
    height: 1000,
    technique: "Center-Focused Airbrush · Twilight Tone",
    finish: "Velvet Gloss",
    nailShape: "Coffin",
    featured: false,
    layer: 2,
  },
  {
    id: "work-027",
    title: "Black Pearl Chrome Micro-Edge",
    category: "Chrome",
    src: "/gallery/work-027.svg",
    alt: "Sheer smoked charcoal base tipped with razor-sharp black pearl chrome metallic edges",
    aspect: "portrait",
    width: 800,
    height: 1000,
    technique: "Black Chrome Rub · Sheer Smoke Foundation",
    finish: "Metallic Noir",
    nailShape: "Almond",
    featured: false,
    layer: 3,
  },
  {
    id: "work-028",
    title: "Terracotta Earth Minimalist Half-Moon",
    category: "Minimal",
    src: "/gallery/work-028.svg",
    alt: "Warm terracotta clay half-moon manicured negative space design on short round nails",
    aspect: "square",
    width: 800,
    height: 800,
    technique: "Lunula Isolation · Earth Pigment",
    finish: "Eggshell Satin",
    nailShape: "Round",
    featured: false,
    layer: 1,
  },
  {
    id: "work-029",
    title: "Abstract Line Art Face Silhouette",
    category: "Nail Art",
    src: "/gallery/work-029.svg",
    alt: "Continuous fine line art profile silhouette hand-drawn on sheer warm porcelain almond nails",
    aspect: "portrait",
    width: 800,
    height: 1000,
    technique: "Single-Stroke Linework · Gel Ink",
    finish: "Glass Shine",
    nailShape: "Almond",
    featured: false,
    layer: 2,
  },
  {
    id: "work-030",
    title: "Diagonal Split Chrome French",
    category: "French",
    src: "/gallery/work-030.svg",
    alt: "Architectural diagonal asymmetric French tip split between mirror gold chrome and creamy nude",
    aspect: "landscape",
    width: 1000,
    height: 750,
    technique: "Precision Tape Stencil · Gold Chrome Powder",
    finish: "Two-Tone Contrast",
    nailShape: "Squoval",
    featured: false,
    layer: 1,
  },
  {
    id: "work-031",
    title: "Deep Olive Matcha Syrup",
    category: "Gel & Care",
    src: "/gallery/work-031.svg",
    alt: "Translucent matcha olive syrup gel manicure with high refractive glass gloss on square tips",
    aspect: "square",
    width: 800,
    height: 800,
    technique: "Syrup Gel Formulation · Clean Cuticle Fold",
    finish: "High-Gloss Glass",
    nailShape: "Square",
    featured: false,
    layer: 2,
  },
  {
    id: "work-032",
    title: "Sculpted Gel Ribbon Flutter",
    category: "Editorial",
    src: "/gallery/work-032.svg",
    alt: "3D sculpted ethereal ribbon loops gracefully crossing sculpted coffin nails with rose chrome sheen",
    aspect: "portrait",
    width: 800,
    height: 1000,
    technique: "Solid 3D Gel Paste · Chrome Powder Dust",
    finish: "Dimensional Ribbon",
    nailShape: "Coffin",
    featured: false,
    layer: 4,
  },
  {
    id: "work-033",
    title: "Champagne Shimmer Sand",
    category: "Chrome",
    src: "/gallery/work-033.svg",
    alt: "Ultra-fine champagne diamond dust shimmer suspended in translucent nude almond gel overlay",
    aspect: "portrait",
    width: 800,
    height: 1000,
    technique: "Micro Flake Infusion · Smooth Glass Topcoat",
    finish: "Sparkling Luster",
    nailShape: "Almond",
    featured: false,
    layer: 1,
  },
  {
    id: "work-034",
    title: "Minimal Gold Cuticle Arc",
    category: "Minimal",
    src: "/gallery/work-034.svg",
    alt: "Bare naked buffed nails with a single hairline metallic gold arc hugging the base cuticle line",
    aspect: "square",
    width: 800,
    height: 800,
    technique: "Metallic Foil Transfer · Clean Natural Nail",
    finish: "Refined Sheen",
    nailShape: "Oval",
    featured: false,
    layer: 2,
  },
  {
    id: "work-035",
    title: "Burgundy French Velvet Tip",
    category: "French",
    src: "/gallery/work-035.svg",
    alt: "Almond manicure with deep burgundy magnetic velvet tips shimmering beneath crystal clear topcoat",
    aspect: "portrait",
    width: 800,
    height: 1000,
    technique: "Deep Velvet Magnet · Nude Rubber Base",
    finish: "Velvet Shimmer Tip",
    nailShape: "Almond",
    featured: false,
    layer: 3,
  },
  {
    id: "work-036",
    title: "The KA Nails Signature Diamond Set",
    category: "Editorial",
    src: "/gallery/work-036.svg",
    alt: "KA Nails signature luxury studio set combining micro-French chrome, 3D drops and sheer rose quartz",
    aspect: "landscape",
    width: 1000,
    height: 750,
    technique: "Full Exhibition Set · Bespoke Mixed Media",
    finish: "Exhibition Masterpiece",
    nailShape: "Almond",
    featured: true,
    layer: 1,
  },
];

export const GALLERY_CATEGORIES: GalleryCategory[] = [
  "All",
  "Minimal",
  "French",
  "Nail Art",
  "Chrome",
  "Gel & Care",
  "Editorial",
];

export function getAllGalleryItems(): GalleryItem[] {
  return GALLERY_ITEMS;
}

export function getFeaturedGalleryItems(): GalleryItem[] {
  return GALLERY_ITEMS.filter((item) => item.featured);
}

export function getHeroGalleryTiles(): GalleryItem[] {
  return GALLERY_ITEMS.slice(0, 4);
}

export function getGalleryItemsByCategory(
  category: GalleryCategory,
): GalleryItem[] {
  if (category === "All") {
    return GALLERY_ITEMS;
  }
  return GALLERY_ITEMS.filter((item) => item.category === category);
}
