// Real KA Nails Work Photography Inventory
// Deterministic source of truth from user-supplied archives (Gmail.zip & Gmail (1).zip)
// Total unique authentic assets: 19 | Fake/synthetic SVGs: 0

export interface SalonPhoto {
  id: string;
  slug: string;
  title: string;
  category: "Classic" | "Color" | "French" | "Glitter / Detail" | "Restorative";
  subCategory: string;
  finish: string;
  colorFamily: string;
  alt: string;
  notes: string;
  featured: boolean;
  heroEligible: boolean;
  heroRole: string;
  isTransformation: boolean;
  aspectRatio: string;
  width: number;
  height: number;
  src: string;
  srcMed: string;
  srcThumb: string;
  srcJpg: string;
}

export const PHOTO_INVENTORY_METRICS = {
  totalFilesProvided: 20,
  uniquePhotos: 19,
  duplicatesRemoved: 1, // IMG_2705.jpeg
  minimumTarget: 30,
  idealTarget: 36,
  additionalPhotosNeededForMinimum: 11,
  additionalPhotosNeededForIdeal: 17,
  inventoryStatus: "INCOMPLETE_MEETS_INITIAL_PORTFOLIO" as const,
};

export const SALON_PHOTOS: SalonPhoto[] = [
  {
    id: "work-01",
    slug: "bordeaux-luxury-editorial",
    title: "Bordeaux Luxury Editorial",
    category: "Classic",
    subCategory: "Pedicure",
    finish: "High-Gloss Gel",
    colorFamily: "Deep Wine / Bordeaux",
    alt: "Deep burgundy bordeaux pedicure with candle, white baby's breath flowers and gold jewelry",
    notes:
      "Editorial still life styling with candle, silk and fresh floral accents",
    featured: true,
    heroEligible: true,
    heroRole: "lead-anchor",
    isTransformation: false,
    aspectRatio: "3:4",
    width: 1086,
    height: 1448,
    src: "/photos/bordeaux-luxury-editorial.webp",
    srcMed: "/photos/bordeaux-luxury-editorial-med.webp",
    srcThumb: "/photos/bordeaux-luxury-editorial-thumb.webp",
    srcJpg: "/photos/bordeaux-luxury-editorial.jpg",
  },
  {
    id: "work-02",
    slug: "royal-cobalt-gloss",
    title: "Royal Cobalt Gloss",
    category: "Color",
    subCategory: "Pedicure",
    finish: "Mirror Gel",
    colorFamily: "Cobalt Blue",
    alt: "Vibrant royal cobalt blue gel pedicure on light grey linen fabric",
    notes: "Crisp square toe contour with high-pigment cobalt blue gel polish",
    featured: true,
    heroEligible: true,
    heroRole: "accent-tile-1",
    isTransformation: false,
    aspectRatio: "1:1",
    width: 1200,
    height: 1200,
    src: "/photos/royal-cobalt-gloss.webp",
    srcMed: "/photos/royal-cobalt-gloss-med.webp",
    srcThumb: "/photos/royal-cobalt-gloss-thumb.webp",
    srcJpg: "/photos/royal-cobalt-gloss.jpg",
  },
  {
    id: "work-03",
    slug: "pastel-lilac-bliss",
    title: "Pastel Lilac Bliss",
    category: "Color",
    subCategory: "Pedicure",
    finish: "Cream Gel",
    colorFamily: "Lilac / Lavender",
    alt: "Soft pastel lilac gel pedicure on white textured spa towel",
    notes:
      "Clean square shaping with immaculate cuticle line and pale lavender finish",
    featured: true,
    heroEligible: true,
    heroRole: "accent-tile-2",
    isTransformation: false,
    aspectRatio: "1:1",
    width: 1200,
    height: 1200,
    src: "/photos/pastel-lilac-bliss.webp",
    srcMed: "/photos/pastel-lilac-bliss-med.webp",
    srcThumb: "/photos/pastel-lilac-bliss-thumb.webp",
    srcJpg: "/photos/pastel-lilac-bliss.jpg",
  },
  {
    id: "work-04",
    slug: "cornflower-sky-closeup",
    title: "Cornflower Sky Macro",
    category: "Color",
    subCategory: "Pedicure",
    finish: "Gloss Gel",
    colorFamily: "Baby Blue",
    alt: "Macro closeup of baby blue square pedicure resting on plush white spa towel",
    notes:
      "Macro studio detail showcasing surface reflection and clean square shaping",
    featured: true,
    heroEligible: true,
    heroRole: "accent-tile-3",
    isTransformation: false,
    aspectRatio: "3:4",
    width: 1200,
    height: 1585,
    src: "/photos/cornflower-sky-closeup.webp",
    srcMed: "/photos/cornflower-sky-closeup-med.webp",
    srcThumb: "/photos/cornflower-sky-closeup-thumb.webp",
    srcJpg: "/photos/cornflower-sky-closeup.jpg",
  },
  {
    id: "work-05",
    slug: "french-yin-yang",
    title: "Minimal French Contrast",
    category: "French",
    subCategory: "Pedicure",
    finish: "French Tip",
    colorFamily: "Sheer Blush / White",
    alt: "Classic French pedicure with crisp white smile lines on sheer blush base with mandala tattoo",
    notes:
      "Precision micro-smile line French styling on sheer translucent base",
    featured: true,
    heroEligible: true,
    heroRole: "accent-tile-4",
    isTransformation: false,
    aspectRatio: "1:1",
    width: 1200,
    height: 1185,
    src: "/photos/french-yin-yang.webp",
    srcMed: "/photos/french-yin-yang-med.webp",
    srcThumb: "/photos/french-yin-yang-thumb.webp",
    srcJpg: "/photos/french-yin-yang.jpg",
  },
  {
    id: "work-06",
    slug: "french-bow-heart-art",
    title: "French Bow & Heart Art",
    category: "Glitter / Detail",
    subCategory: "Pedicure",
    finish: "Hand-Painted Nail Art",
    colorFamily: "White / Natural Pink",
    alt: "French pedicure featuring delicate hand-painted white bow and heart motifs on big toes",
    notes: "Hand-drawn micro bow and heart illustration on big toe tips",
    featured: true,
    heroEligible: true,
    heroRole: "accent-tile-5",
    isTransformation: false,
    aspectRatio: "1:1",
    width: 1200,
    height: 1135,
    src: "/photos/french-bow-heart-art.webp",
    srcMed: "/photos/french-bow-heart-art-med.webp",
    srcThumb: "/photos/french-bow-heart-art-thumb.webp",
    srcJpg: "/photos/french-bow-heart-art.jpg",
  },
  {
    id: "work-07",
    slug: "rose-quartz-shimmer",
    title: "Rose Quartz Shimmer",
    category: "Glitter / Detail",
    subCategory: "Pedicure",
    finish: "Glitter / Shimmer",
    colorFamily: "Pink Shimmer",
    alt: "Sparkling rose quartz glitter pedicure with multidimensional pink micro-glitter",
    notes: "High-density micro-glitter suspension with prism light reflection",
    featured: true,
    heroEligible: true,
    heroRole: "accent-tile-6",
    isTransformation: false,
    aspectRatio: "1:1",
    width: 1200,
    height: 1121,
    src: "/photos/rose-quartz-shimmer.webp",
    srcMed: "/photos/rose-quartz-shimmer-med.webp",
    srcThumb: "/photos/rose-quartz-shimmer-thumb.webp",
    srcJpg: "/photos/rose-quartz-shimmer.jpg",
  },
  {
    id: "work-08",
    slug: "scarlet-red-lacquer",
    title: "Classic Scarlet Lacquer",
    category: "Classic",
    subCategory: "Pedicure",
    finish: "High-Gloss",
    colorFamily: "True Red",
    alt: "Vibrant classic scarlet red pedicure with brilliant mirror shine",
    notes: "Timeless deep scarlet salon lacquer with ultra-glossy topcoat",
    featured: true,
    heroEligible: false,
    heroRole: "gallery-item",
    isTransformation: false,
    aspectRatio: "1:1",
    width: 1200,
    height: 1142,
    src: "/photos/scarlet-red-lacquer.webp",
    srcMed: "/photos/scarlet-red-lacquer-med.webp",
    srcThumb: "/photos/scarlet-red-lacquer-thumb.webp",
    srcJpg: "/photos/scarlet-red-lacquer.jpg",
  },
  {
    id: "work-09",
    slug: "alabaster-pure-white",
    title: "Alabaster Pure White",
    category: "Classic",
    subCategory: "Pedicure",
    finish: "Opaque Gloss",
    colorFamily: "Pure White",
    alt: "Crisp alabaster white pedicure on draped linen fabric",
    notes: "Full-coverage bright white gel with geometric square contour",
    featured: true,
    heroEligible: false,
    heroRole: "gallery-item",
    isTransformation: false,
    aspectRatio: "3:4",
    width: 1200,
    height: 1488,
    src: "/photos/alabaster-pure-white.webp",
    srcMed: "/photos/alabaster-pure-white-med.webp",
    srcThumb: "/photos/alabaster-pure-white-thumb.webp",
    srcJpg: "/photos/alabaster-pure-white.jpg",
  },
  {
    id: "work-10",
    slug: "midnight-onyx-gloss",
    title: "Midnight Onyx Gloss",
    category: "Classic",
    subCategory: "Pedicure",
    finish: "Mirror Gel",
    colorFamily: "Jet Black",
    alt: "High-gloss mirror jet black pedicure resting on neutral linen",
    notes: "Deep opaque black gel with liquid mirror finish",
    featured: false,
    heroEligible: false,
    heroRole: "gallery-item",
    isTransformation: false,
    aspectRatio: "1:1",
    width: 1200,
    height: 1124,
    src: "/photos/midnight-onyx-gloss.webp",
    srcMed: "/photos/midnight-onyx-gloss-med.webp",
    srcThumb: "/photos/midnight-onyx-gloss-thumb.webp",
    srcJpg: "/photos/midnight-onyx-gloss.jpg",
  },
  {
    id: "work-11",
    slug: "champagne-platinum-glitter",
    title: "Champagne Platinum Glitter",
    category: "Glitter / Detail",
    subCategory: "Pedicure",
    finish: "Reflective Glitter",
    colorFamily: "Champagne Gold",
    alt: "Champagne platinum glitter pedicure with dense metallic reflection",
    notes:
      "Dense platinum champagne reflective shimmer with square toe profile",
    featured: false,
    heroEligible: false,
    heroRole: "gallery-item",
    isTransformation: false,
    aspectRatio: "1:1",
    width: 1200,
    height: 1160,
    src: "/photos/champagne-platinum-glitter.webp",
    srcMed: "/photos/champagne-platinum-glitter-med.webp",
    srcThumb: "/photos/champagne-platinum-glitter-thumb.webp",
    srcJpg: "/photos/champagne-platinum-glitter.jpg",
  },
  {
    id: "work-12",
    slug: "porcelain-nude-spa",
    title: "Porcelain Nude Natural",
    category: "Classic",
    subCategory: "Pedicure",
    finish: "Sheer Nude",
    colorFamily: "Milky Nude",
    alt: "Porcelain nude pedicure on draped cream salon blanket with fringed edge",
    notes: "Understated sheer milky pink nude gel with natural healthy sheen",
    featured: false,
    heroEligible: false,
    heroRole: "gallery-item",
    isTransformation: false,
    aspectRatio: "4:5",
    width: 1200,
    height: 1472,
    src: "/photos/porcelain-nude-spa.webp",
    srcMed: "/photos/porcelain-nude-spa-med.webp",
    srcThumb: "/photos/porcelain-nude-spa-thumb.webp",
    srcJpg: "/photos/porcelain-nude-spa.jpg",
  },
  {
    id: "work-13",
    slug: "peach-melon-cream",
    title: "Peach Melon Cream",
    category: "Color",
    subCategory: "Pedicure",
    finish: "Cream Gel",
    colorFamily: "Peach / Coral",
    alt: "Warm pastel peach melon cream pedicure on clean white backdrop",
    notes: "Summer-fresh coral peach pastel with smooth uniform coverage",
    featured: false,
    heroEligible: false,
    heroRole: "gallery-item",
    isTransformation: false,
    aspectRatio: "1:1",
    width: 1200,
    height: 1072,
    src: "/photos/peach-melon-cream.webp",
    srcMed: "/photos/peach-melon-cream-med.webp",
    srcThumb: "/photos/peach-melon-cream-thumb.webp",
    srcJpg: "/photos/peach-melon-cream.jpg",
  },
  {
    id: "work-14",
    slug: "indigo-denim-gloss",
    title: "Indigo Denim Gloss",
    category: "Color",
    subCategory: "Pedicure",
    finish: "Gloss Gel",
    colorFamily: "Indigo Blue",
    alt: "Deep indigo denim blue pedicure on medical-grade salon paper",
    notes:
      "Rich twilight indigo blue pigment with square precision cuticle lines",
    featured: false,
    heroEligible: false,
    heroRole: "gallery-item",
    isTransformation: false,
    aspectRatio: "1:1",
    width: 1200,
    height: 1212,
    src: "/photos/indigo-denim-gloss.webp",
    srcMed: "/photos/indigo-denim-gloss-med.webp",
    srcThumb: "/photos/indigo-denim-gloss-thumb.webp",
    srcJpg: "/photos/indigo-denim-gloss.jpg",
  },
  {
    id: "work-15",
    slug: "rose-shimmer-french",
    title: "Rose Shimmer French",
    category: "French",
    subCategory: "Pedicure",
    finish: "French with Shimmer",
    colorFamily: "Pink Shimmer / White",
    alt: "French pedicure with sparkling shimmer pink base and crisp white micro-tips",
    notes:
      "Subtle luminous pink shimmer base paired with sharp clean French smiling curves",
    featured: false,
    heroEligible: false,
    heroRole: "gallery-item",
    isTransformation: false,
    aspectRatio: "4:5",
    width: 1200,
    height: 1507,
    src: "/photos/rose-shimmer-french.webp",
    srcMed: "/photos/rose-shimmer-french-med.webp",
    srcThumb: "/photos/rose-shimmer-french-thumb.webp",
    srcJpg: "/photos/rose-shimmer-french.jpg",
  },
  {
    id: "work-16",
    slug: "cornflower-blue-drape",
    title: "Cornflower Blue Drape",
    category: "Color",
    subCategory: "Pedicure",
    finish: "Cream Gel",
    colorFamily: "Sky Blue",
    alt: "Soft cornflower sky blue pedicure draped on sheer white textile",
    notes: "Powder blue pastel pedicure set against soft folded textile",
    featured: false,
    heroEligible: false,
    heroRole: "gallery-item",
    isTransformation: false,
    aspectRatio: "1:1",
    width: 1200,
    height: 1086,
    src: "/photos/cornflower-blue-drape.webp",
    srcMed: "/photos/cornflower-blue-drape-med.webp",
    srcThumb: "/photos/cornflower-blue-drape-thumb.webp",
    srcJpg: "/photos/cornflower-blue-drape.jpg",
  },
  {
    id: "work-17",
    slug: "french-toe-ring-accent",
    title: "French Toe-Ring Accent",
    category: "French",
    subCategory: "Pedicure",
    finish: "Classic French",
    colorFamily: "Blush / White",
    alt: "Classic French pedicure with silver band toe-ring accent",
    notes:
      "Elegant traditional French pedicure complemented by minimalist silver toe jewelry",
    featured: false,
    heroEligible: false,
    heroRole: "gallery-item",
    isTransformation: false,
    aspectRatio: "4:5",
    width: 1200,
    height: 1359,
    src: "/photos/french-toe-ring-accent.webp",
    srcMed: "/photos/french-toe-ring-accent-med.webp",
    srcThumb: "/photos/french-toe-ring-accent-thumb.webp",
    srcJpg: "/photos/french-toe-ring-accent.jpg",
  },
  {
    id: "work-18",
    slug: "deep-bordeaux-studio-portrait",
    title: "Deep Bordeaux Studio Portrait",
    category: "Classic",
    subCategory: "Pedicure",
    finish: "High-Gloss",
    colorFamily: "Bordeaux Wine",
    alt: "Full-frame portrait of deep bordeaux wine pedicure with high reflective sheen",
    notes:
      "Auto-rotated high-resolution salon master shot of deep wine pedicure",
    featured: false,
    heroEligible: false,
    heroRole: "gallery-item",
    isTransformation: false,
    aspectRatio: "3:4",
    width: 1200,
    height: 1600,
    src: "/photos/deep-bordeaux-studio-portrait.webp",
    srcMed: "/photos/deep-bordeaux-studio-portrait-med.webp",
    srcThumb: "/photos/deep-bordeaux-studio-portrait-thumb.webp",
    srcJpg: "/photos/deep-bordeaux-studio-portrait.jpg",
  },
  {
    id: "work-19",
    slug: "restorative-aesthetic-transformation",
    title: "Restorative Aesthetic Pedicure",
    category: "Restorative",
    subCategory: "Pedicure",
    finish: "Restorative Care",
    colorFamily: "Scarlet Red / Natural Care",
    alt: "Restorative aesthetic pedicure transformation showing professional nail revitalization and red finish",
    notes:
      "Clinical before & after demonstration of precision nail bed restoration and polish",
    featured: false,
    heroEligible: false,
    heroRole: "gallery-item",
    isTransformation: true,
    aspectRatio: "3:4",
    width: 1200,
    height: 1715,
    src: "/photos/restorative-aesthetic-transformation.webp",
    srcMed: "/photos/restorative-aesthetic-transformation-med.webp",
    srcThumb: "/photos/restorative-aesthetic-transformation-thumb.webp",
    srcJpg: "/photos/restorative-aesthetic-transformation.jpg",
  },
];

export const HERO_PHOTOS = SALON_PHOTOS.filter((p) => p.heroEligible);
export const FEATURED_PHOTOS = SALON_PHOTOS.filter((p) => p.featured);
export const HOMEPAGE_WALL_PHOTOS = SALON_PHOTOS.slice(0, 12);
export const GALLERY_PHOTOS = SALON_PHOTOS;
