// Copies the self-hosted font subsets the site needs (Latin + Cyrillic) from
// the @fontsource-variable packages to public/fonts/ under stable URLs and
// writes app/fonts.css. Stable URLs let the layouts preload the fonts, so the
// first paint already uses them and the font swap causes no layout shift.
import fs from "node:fs/promises";
import path from "node:path";

const sources = [
  "@fontsource-variable/inter/index.css",
  "@fontsource-variable/cormorant-garamond/index.css",
  "@fontsource-variable/cormorant-garamond/wght-italic.css",
];
const keepSubsets = ["latin", "latin-ext", "cyrillic", "cyrillic-ext"];
const outDir = path.resolve("public/fonts");
await fs.rm(outDir, { recursive: true, force: true });
await fs.mkdir(outDir, { recursive: true });

const blocks = [];
for (const source of sources) {
  const cssPath = path.resolve("node_modules", source);
  const css = await fs.readFile(cssPath, "utf8");
  for (const match of css.matchAll(
    /\/\* ([\w-]+) \*\/\s*(@font-face \{[^}]*\})/g,
  )) {
    const [, name, block] = match;
    const subset = name.replace(
      /^.*?-((?:latin|cyrillic|greek|vietnamese)(?:-ext)?)-wght-(?:normal|italic)$/,
      "$1",
    );
    if (!keepSubsets.includes(subset)) continue;
    const file = block.match(/url\(\.\/files\/([^)]+\.woff2)\)/)[1];
    await fs.copyFile(
      path.join(path.dirname(cssPath), "files", file),
      path.join(outDir, file),
    );
    blocks.push(
      `/* ${name} */\n` +
        block
          .replace(/src: [^;]+;/, `src: url("/fonts/${file}") format("woff2");`)
          .replace(/\n\s*/g, "\n  ")
          .replace(/\n  \}$/, "\n}"),
    );
  }
}

await fs.writeFile(
  path.resolve("app/fonts.css"),
  "/* Generated by tools/sync-fonts.mjs from @fontsource-variable packages. */\n\n" +
    blocks.join("\n\n") +
    "\n",
);
console.log(`${blocks.length} font faces → public/fonts, app/fonts.css`);
